# Generated by Django 5.1.6 on 2025-04-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_todoitem_delete_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoItem",
            new_name="Task",
        ),
    ]
